// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UndergroundFootballStadium_UFSAPI.Data;

#nullable disable

namespace UndergroundFootballStadium_UFSAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UndergroundFootballStadium_UFSAPI.Models.UFS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UFSs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Football",
                            CreatedDate = new DateTime(2024, 9, 19, 12, 35, 29, 156, DateTimeKind.Local).AddTicks(1397),
                            Details = "Mirpur UFS is a football stadium located in Mirpur, Dhaka, Bangladesh. It is the home of the Bangladesh national football team and Abahani Limited Dhaka. The stadium goes by the nickname 'The Cauldron'.",
                            ImageUrl = "",
                            Name = "Kings Arena",
                            Occupancy = 10,
                            Rate = 5000.0,
                            Sqft = 10000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Football",
                            CreatedDate = new DateTime(2024, 9, 19, 12, 35, 29, 156, DateTimeKind.Local).AddTicks(1411),
                            Details = "Old Trafford is a football stadium in Old Trafford, Greater Manchester, England, and the home of Manchester United. With a capacity of 74,140 seats, it is the largest club football stadium in the United Kingdom, and the eleventh-largest in Europe.",
                            ImageUrl = "",
                            Name = "Old Trafford",
                            Occupancy = 5,
                            Rate = 25000.0,
                            Sqft = 12000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Football",
                            CreatedDate = new DateTime(2024, 9, 19, 12, 35, 29, 156, DateTimeKind.Local).AddTicks(1412),
                            Details = "Camp Nou is the home stadium of FC Barcelona since its completion in 1957. With a seating capacity of 99,354, it is the largest stadium in Spain and Europe, and the third largest football stadium in the world in capacity.",
                            ImageUrl = "",
                            Name = "Camp Nou",
                            Occupancy = 7,
                            Rate = 2000.0,
                            Sqft = 15000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Football",
                            CreatedDate = new DateTime(2024, 9, 19, 12, 35, 29, 156, DateTimeKind.Local).AddTicks(1413),
                            Details = "The Santiago Bernabéu Stadium is a football stadium in Madrid, Spain. With a current seating capacity of 81,044, it has been the home stadium of Real Madrid since its completion in 1947.",
                            ImageUrl = "",
                            Name = "Santiago Bernabeu",
                            Occupancy = 2,
                            Rate = 60000.0,
                            Sqft = 18000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
