//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
